x-pyflink: &pyflink
  build: ./pyflink
  image: pyflink:2.2.1


services:
  # There is an example for the environment variables at https://hub.docker.com/r/apache/kafka.
  # But I only need the default for the moment.
  broker:
    image: apache/kafka:latest
    container_name: broker
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true" # This does not work with pyflink.
    ports: # This forwards the ports from the container to localhost.
      - "9092:9092"

  kafbat-ui:
    container_name: kafbat-ui
    image: ghcr.io/kafbat/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - broker
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      SWAGGER_UI_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: broker
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:9092

  # Flink in standalone (we manage the containers ourselves) session (one cluster to which we send jobs) mode.
  # From https://nightlies.apache.org/flink/flink-docs-release-2.2/docs/deployment/resource-providers/standalone/docker/
  jobmanager:
    <<: *pyflink
    container_name: jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    volumes:
      - paimon_tmp:/tmp
    environment: # 'jobmanager.rpc.address: jobmanager' makes the address point to the 'jobmanager' service.
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager

  taskmanager:
    <<: *pyflink
    container_name: taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    volumes:
      - paimon_tmp:/tmp
    scale: 1 # We use a single task manager for development. It can still have multiple task slots.
    # The '-' makes it be an element in a list (environment contains one item, FLINK_PROPERTIES) 
    # and '|' makes the string contain multiple lines as in the input.
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 5

networks:
  default:
    name: i2r-network

volumes:
  paimon_tmp:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=256m   # adjust size as needed